name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Verify formatting
        run: echo "Volkswagen Test FTW"
